sudo: required

services:
    - docker

before_install:
    - docker pull alediaferia/electra

script:
    - docker run alediaferia/electra /bin/bash -c "su - ecadev; git clone -b $TRAVIS_BRANCH --single-branch https://github.com/Electra-project/Electra.git; cd Electra; qmake; make"
